[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[build.environment]
  PHP_VERSION = "8.4"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

